import { Meteor } from '../types/types';

export const randomRotation = (): number => Math.floor(Math.random() * 360) + 1;
export const randomBcg = (): number => Math.floor(Math.random() * 5) + 1;

export const TIME_PER_LEVEL = 90;
export const SPEED_1 = 10;
export const SPEED_2 = 20;
export const ASTRONAUTS = 5;
export const SHIP_SPEED_MODIFIER = 5;
export const SHIP_INITAL_Y = 225;
export const SHIP_INITAL_X = 200;
export const COLLISION_ZONE_X1 = 255;
export const COLLISION_ZONE_X2 = 347;
export const METEOR_SPEED = 1;
export const SCORE_PER_ASTRONAUT = 500;

export const initCollisionPointsX = {
  P1: SHIP_INITAL_X + 55,
  P2: SHIP_INITAL_X + 72,
  P3: SHIP_INITAL_X + 88,
  P4: SHIP_INITAL_X + 99,
  P5: SHIP_INITAL_X + 112,
  P6: SHIP_INITAL_X + 126,
  P7: SHIP_INITAL_X + 139,
  P8: SHIP_INITAL_X + 147,
  P9: SHIP_INITAL_X + 138,
  P10: SHIP_INITAL_X + 126,
  P11: SHIP_INITAL_X + 113,
  P12: SHIP_INITAL_X + 100,
  P13: SHIP_INITAL_X + 89,
  P14: SHIP_INITAL_X + 72,
  P15: SHIP_INITAL_X + 54,
};

export const initCollisionPointsY = {
  P1: SHIP_INITAL_Y + 2,
  P2: SHIP_INITAL_Y + 2,
  P3: SHIP_INITAL_Y + 3,
  P4: SHIP_INITAL_Y + 9,
  P5: SHIP_INITAL_Y + 11,
  P6: SHIP_INITAL_Y + 15,
  P7: SHIP_INITAL_Y + 20,
  P8: SHIP_INITAL_Y + 29,
  P9: SHIP_INITAL_Y + 38,
  P10: SHIP_INITAL_Y + 44,
  P11: SHIP_INITAL_Y + 47,
  P12: SHIP_INITAL_Y + 49,
  P13: SHIP_INITAL_Y + 59,
  P14: SHIP_INITAL_Y + 60,
  P15: SHIP_INITAL_Y + 62,
};
export const meteors: Meteor[] = [
  {
    id: 100,
    size: 50,
    x: 810,
    y: 105,
    bcg: 6,
    rotation: 0,
    astronaut: true,
  },
  {
    id: 101,
    size: 50,
    x: 5300,
    y: 0,
    bcg: 7,
    rotation: 0,
    astronaut: true,
  },
  {
    id: 102,
    size: 50,
    x: 1920,
    y: 150,
    bcg: 8,
    rotation: 0,
    astronaut: true,
  },
  {
    id: 103,
    size: 50,
    x: 4420,
    y: 300,
    bcg: 9,
    rotation: 0,
    astronaut: true,
  },
  {
    id: 104,
    size: 50,
    x: 2990,
    y: 45,
    bcg: 10,
    rotation: 0,
    astronaut: true,
  },
  {
    id: 54,
    size: 200,
    x: 1100,
    y: 300,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 55,
    size: 60,
    x: 950,
    y: 30,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 56,
    size: 80,
    x: 800,
    y: 150,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 57,
    size: 50,
    x: 700,
    y: 370,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 0,
    size: 35,
    x: 1230,
    y: 10,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 1,
    size: 50,
    x: 1300,
    y: 410,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 2,
    size: 90,
    x: 1200,
    y: 90,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 3,
    size: 100,
    x: 1600,
    y: 50,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 4,
    size: 70,
    x: 1920,
    y: 210,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 5,
    size: 170,
    x: 1570,
    y: 350,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 6,
    size: 35,
    x: 2170,
    y: 380,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 7,
    size: 40,
    x: 1970,
    y: 100,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 8,
    size: 45,
    x: 2270,
    y: 400,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 9,
    size: 80,
    x: 1470,
    y: 150,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 10,
    size: 35,
    x: 1470,
    y: 350,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 11,
    size: 70,
    x: 2370,
    y: 30,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 12,
    size: 35,
    x: 3470,
    y: 320,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 13,
    size: 220,
    x: 3430,
    y: -60,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 14,
    size: 35,
    x: 2230,
    y: 10,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 15,
    size: 50,
    x: 2450,
    y: 430,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 16,
    size: 90,
    x: 2200,
    y: 90,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 17,
    size: 100,
    x: 2600,
    y: 50,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 18,
    size: 70,
    x: 2970,
    y: 250,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 19,
    size: 170,
    x: 2870,
    y: 410,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 20,
    size: 35,
    x: 4070,
    y: 410,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 21,
    size: 35,
    x: 3170,
    y: 380,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 22,
    size: 40,
    x: 2990,
    y: 90,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 23,
    size: 40,
    x: 3270,
    y: 400,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 24,
    size: 80,
    x: 2470,
    y: 150,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 25,
    size: 35,
    x: 2470,
    y: 350,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 26,
    size: 70,
    x: 3170,
    y: 150,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 27,
    size: 220,
    x: 3670,
    y: 280,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 28,
    size: 35,
    x: 3800,
    y: 40,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 29,
    size: 50,
    x: 4750,
    y: 310,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 31,
    size: 100,
    x: 4100,
    y: 200,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 32,
    size: 70,
    x: 4420,
    y: 210,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 33,
    size: 170,
    x: 4070,
    y: 350,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 34,
    size: 35,
    x: 4670,
    y: 380,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 35,
    size: 40,
    x: 4470,
    y: 100,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 36,
    size: 40,
    x: 4770,
    y: 400,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 37,
    size: 80,
    x: 3970,
    y: 150,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 38,
    size: 35,
    x: 3970,
    y: 350,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 39,
    size: 70,
    x: 4870,
    y: 30,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 40,
    size: 35,
    x: 5970,
    y: 320,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 41,
    size: 220,
    x: 5870,
    y: -40,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 42,
    size: 35,
    x: 4730,
    y: 10,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 43,
    size: 50,
    x: 4950,
    y: 430,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 44,
    size: 90,
    x: 4700,
    y: 90,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 45,
    size: 100,
    x: 5100,
    y: 50,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 46,
    size: 70,
    x: 5470,
    y: 250,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 47,
    size: 170,
    x: 5370,
    y: 410,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 48,
    size: 35,
    x: 4700,
    y: 410,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 49,
    size: 35,
    x: 5000,
    y: 310,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 50,
    size: 35,
    x: 5300,
    y: 250,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 51,
    size: 35,
    x: 5800,
    y: 50,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 52,
    size: 35,
    x: 5600,
    y: 150,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
  {
    id: 53,
    size: 35,
    x: 5800,
    y: 350,
    bcg: randomBcg(),
    rotation: randomRotation(),
  },
];
